#!/usr/bin/env bash
set -e

inject=../Lua/inject
rom=../../roms/everything/"Legend of Zelda, The - Ocarina of Time - Master Quest (E) (Debug) [f1].z64"
lips=../Lua/lib/lips
out=oot-widescreen.z64

. common.sh

luajit patch.lua \
  -O 0x035D0000 -b $((0x80700000 - 0x035D0000)) \
  widescreen-inline.asm "$out"

dump -f patch/build/"$out"
