#!/usr/bin/env bash
set -e

inject=../Lua/inject
rom=../roms/everything/"Legend of Zelda, The - Ocarina of Time - Master Quest (E) (Debug) [f1].z64"
lips=../Lua/lib/lips
out=oot-spawner.z64

mkdir -p build
cp *.lua build/
cd build

cp ../../"$rom" "$out"

# don't copy entire dir; avoid copying dotfiles (.git)
mkdir -p lips
cp ../"$lips"/* lips

cp ../"$inject/"*.asm .
cp ../*.asm .

luajit patch.lua -o 0 \
  --extra-rom 0x035D0000 --extra-ram 0x80700000 \
  'spawn O EUDB MQ.asm' "$out"

(cd ../../; ./z64dump.py -f patch/build/"$out")
